server:
  port: 9090
#  servlet:
#    context-path:

#base
spring:
  thymeleaf:
    cache: false

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_community?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 链接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
  # 邮箱 参数
  mail:
    host:
    port:
    username:
    password:
    # 加密
    protocol:
    properties:
      mail:
        smtp:
          ssl:
            enable: true

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pres.hjc.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true


# domain
community:
    path:
      domain: 1111111

